globalAnnotations: {}

storage:
  name: storage-minio
  package: ghcr.io/versioneer-tech/provider-storage/minio:0.2.0
  annotations: {}

datalab:
  name: datalab-educates
  package: ghcr.io/versioneer-tech/provider-datalab/educates:0.4.2
  annotations: {}

environmentconfig:
  name: datalab
  annotations: {}
  iam:
    realm: ""
  ingress:
    class: ""
    domain: ""
    secret: ""
  storage:
    endpoint: ""
    forcePathStyle: true
    provider: ""
    region: ""
    secretNamespace: ""
    type: s3
  network:
    serviceCIDR: ""
  packages: []
  auth:
    type: ""
  defaults:
    quota:
      memory: ""
      storage: ""
      budget: ""
    security:
      policy: ""
      kubernetesAccess: ""
      kubernetesRole: ""
  database: 
    gateway:
      parentName: ""
      parentNamespace: ""
      sectionName: ""
    storageClassName: ""
    backupStorageClassName: ""